# Generated by Django 5.2.7 on 2025-10-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_activation_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "permissions": [
                    ("can_block_user", "can_block_user"),
                    ("can_view_user", "can_view_user"),
                    ("can_add_user", "can_add_user"),
                    ("can_change_user", "can_change_user"),
                    ("can_delete_user", "can_delete_user"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="user",
        ),
    ]
