# Generated by Django 5.2.6 on 2025-09-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_sending", "status", "is_active"],
                "permissions": [("block_mailing", "Блокировка рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelTable(
            name="mailing",
            table="mailing",
        ),
    ]
