# Generated by Django 5.2.6 on 2025-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0002_alter_mailing_options_alter_mailing_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
