# Generated by Django 5.2.6 on 2025-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0003_alter_mailing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
