# Generated by Django 5.2.6 on 2025-09-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0004_message_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("block_message", "Блокировка сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelTable(
            name="message",
            table="message",
        ),
    ]
