# Generated by Django 5.2.6 on 2025-09-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0006_messagerecipient_is_active_messagerecipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagerecipient",
            options={
                "permissions": [("deactivate_recipient", "Деактивация получателя")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelTable(
            name="messagerecipient",
            table="recipient",
        ),
    ]
