# Generated by Django 5.2.6 on 2025-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0007_alter_messagerecipient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["date_attempt"],
                "permissions": [("block_mailing_attempt", "Блокировка попытки рассылки")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="mailingattempt",
            table="mailing_attempt",
        ),
    ]
