# Generated by Django 5.2.6 on 2025-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0008_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("SUCCESSFULLY", "Успешно"), ("NOT SUCCESSFUL", "Запущена")],
                default="SUCCESSFULLY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="date_attempt",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
