# Generated by Django 5.2.6 on 2025-10-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0009_mailingattempt_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_attempts",
                to="sending.messagerecipient",
            ),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_attempts",
                to="sending.messagerecipient",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("SUCCESSFULLY", "Успешно"), ("UNSUCCESSFULY", "Неуспешно")],
                default="SUCCESSFULLY",
                max_length=20,
            ),
        ),
    ]
