# Generated by Django 5.2.6 on 2025-10-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0010_mailingattempt_owner_mailingattempt_recipient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["attempted_at"],
                "permissions": [("block_mailing_attempt", "Блокировка попытки рассылки")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="date_attempt",
            new_name="attempted_at",
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("SUCCESSFULLY", "Успешно"), ("UNSUCCESSFULLY", "Неуспешно")],
                default="SUCCESSFULLY",
                max_length=20,
            ),
        ),
    ]
