# Generated by Django 5.2.6 on 2025-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0011_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="recipient",
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipient_attempts", to="sending.messagerecipient"
            ),
        ),
    ]
