# Generated by Django 5.2.6 on 2025-10-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0012_remove_mailingattempt_recipient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="recipient",
            new_name="recipients",
        ),
    ]
