# Generated by Django 5.2.6 on 2025-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0013_rename_recipient_mailingattempt_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="recipients",
            field=models.ManyToManyField(related_name="recipient_attempts", to="sending.messagerecipient"),
        ),
    ]
