# Generated by Django 5.2.6 on 2025-10-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0014_alter_mailingattempt_recipients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="mailingattempt",
            name="recipients",
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_attempts",
                to="sending.messagerecipient",
            ),
        ),
    ]
