# Generated by Django 5.2.6 on 2025-10-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0015_remove_mailingattempt_is_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mailingattempt",
            unique_together={("mailing", "recipient")},
        ),
    ]
