# Generated by Django 5.2.6 on 2025-10-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0016_alter_mailingattempt_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt_set",
                to="sending.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
