# Generated by Django 5.2.6 on 2025-10-10 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0017_alter_mailingattempt_mailing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
