# Generated by Django 5.2.7 on 2025-10-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0018_alter_mailingattempt_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_sending", "status", "is_active"],
                "permissions": [("can_block_mailing", "can_block_mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["attempted_at"],
                "permissions": [
                    ("can_block_mailing_attempt", "can_block_mailing_attempt"),
                    ("can_add_mailing_attempt", "can_add_mailing_attempt"),
                    ("can_view_mailing_attempt", "can_view_mailing_attempt"),
                    ("can_change_mailing_attempt", "can_change_mailing_attempt"),
                    ("can_delete_mailing_attempt", "can_delete_mailing_attempt"),
                ],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_block_message", "can_block_message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="messagerecipient",
            options={
                "permissions": [
                    ("can_deactivate_recipient", "can_deactivate_recipient"),
                    ("can_add_recipient", "can_add_recipient"),
                    ("can_view_recipient", "can_view_recipient"),
                    ("can_change_recipient", "can_change_recipient"),
                    ("can_delete_recipient", "can_delete_recipient"),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
